import { NODE_ENV } from './envs';

// constants.ts
export const ACCESS_TOKEN_EXPIRY = '15m';
export const REFRESH_TOKEN_EXPIRY = '7d';
export const REFRESH_TOKEN_EXPIRY_MS = 7 * 24 * 60 * 60 * 1000;

export const EMAIL_VERIFICATION_TOKEN_EXPIRY = '10m';

export const COOKIE_OPTIONS = {
  httpOnly: true,
  secure: NODE_ENV === 'production',
  maxAge: 7 * 24 * 60 * 60 * 1000, // 7 days
};

export const ERROR_CODES = {
  // User & Auth
  EMAIL_EXISTS: 'EMAIL_EXISTS',
  USERNAME_EXISTS: 'USERNAME_EXISTS',
  PHONE_EXISTS: 'PHONE_EXISTS',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  ACCOUNT_DISABLED: 'ACCOUNT_DISABLED',
  UNAUTHORIZED: 'UNAUTHORIZED',

  // Tokens & Sessions
  REFRESH_TOKEN_INVALID: 'INVALID_REFRESH_TOKEN',
  REFRESH_TOKEN_MISSING: 'REFRESH_TOKEN_MISSING',
  ACCESS_TOKEN_EXPIRED: 'ACCESS_TOKEN_EXPIRED',
  ACCESS_TOKEN_NOT_FOUND: 'ACCESS_TOKEN_NOT_FOUND',
  ACCESS_TOKEN_INVALID: 'ACCESS_TOKEN_INVALID',
  SESSION_NOT_FOUND: 'SESSION_NOT_FOUND',
  TOKEN_VERIFICATION_FAILED: 'TOKEN_VERIFICATION_FAILED',
  INVALID_HASH: 'INVALID_HASH',

  // Input & Validation
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  MISSING_REQUIRED_FIELDS: 'MISSING_REQUIRED_FIELDS',
  INVALID_EMAIL_FORMAT: 'INVALID_EMAIL_FORMAT',

  // Permissions / Roles
  FORBIDDEN: 'FORBIDDEN',
  ROLE_NOT_ALLOWED: 'ROLE_NOT_ALLOWED',

  // Resource Errors
  NOT_FOUND: 'NOT_FOUND',
  RESOURCE_CONFLICT: 'RESOURCE_CONFLICT',

  // Server/Internal
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  DATABASE_ERROR: 'DATABASE_ERROR',
  EXTERNAL_SERVICE_ERROR: 'EXTERNAL_SERVICE_ERROR',

  // File Upload / Storage
  FILE_TOO_LARGE: 'FILE_TOO_LARGE',
  UNSUPPORTED_FILE_TYPE: 'UNSUPPORTED_FILE_TYPE',

  // Rate Limiting / Throttling
  TOO_MANY_REQUESTS: 'TOO_MANY_REQUESTS',

  // Generic fallback
  UNKNOWN_ERROR: 'UNKNOWN_ERROR',
};
